### ISSUE TITLE
Every command should have a different transaction number

### ISSUE THREAD

**Issue by kawal97** [RajathInuganti/SENG468#32]
Each command that is processed in the transaction server should have a unique transaction number. 
Requirements:
command 1 should have transaction number 1
command n ........................  transaction number n

**Comment by RajathInuganti** [comment]
Can we make the transaction number as part of the `command` struct that we're sending in from cli.go, i.e, another `int` field in the `struct` ? Lmk what you think.

**Comment by siddhant-28** [comment]
> Can we make the transaction number as part of the `command` struct that we're sending in from cli.go, i.e, another `int` field in the `struct` ? Lmk what you think.

I agree with this. Should be easier than generating it from the web server

**Comment by kawal97** [comment]
hmm.. I don't agree. Transaction number should be assigned by the tx server. Because there will be transactions that the tx server will do on its own. For example: executing a trigger. This transaction will be a system event, and will be isolated & independent of the actual `SET_BUY_TRIGGER` command that was sent by the user.

**Comment by kawal97** [comment]
I have sent a message to the TA to confirm if system event log(when the trigger executes) should have the same transaction number as the corresponding SET_BUY_TRIGGER command..
