### ISSUE TITLE
Refactor to enable multiple workers

### ISSUE THREAD

**Issue by kawal97** [RajathInuganti/SENG468#67]

**Comment by RajathInuganti** [comment]
Taking care of this starting tomorrow evening.

**Comment by RajathInuganti** [comment]
Initialize "common" queue used to push the name of transaction server/web server container instance (as we will use the same name for the queue).
use the communicated queue name to publish requests/responses.
assign each user a txserver (basically the queue that is used to stick requests to that txserver).
