### ISSUE TITLE
look into gRPC implementation

### ISSUE THREAD

**Issue by kawal97** [RajathInuganti/SENG468#70]
![image](https://user-images.githubusercontent.com/39280329/156926632-da473155-1bdd-4ec0-9b95-eed66bf48b35.png)

[link](https://blog.dreamfactory.com/grpc-vs-rest-how-does-grpc-compare-with-traditional-rest-apis/#:~:text=%E2%80%9CgRPC%20is%20roughly%207%20times,HTTP%2F2%20by%20gRPC.%E2%80%9D)

**Comment by RajathInuganti** [comment]
We do not have time for this atm I think
